[project]
name = "west-consumer"
version = "0.1.0"
description = "West Consumer"
authors = [
    {name = "lukaszlacinski", email = "lukasz@uchicago.edu"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "esgf-core-utils>=1.0.7",
]

[project.optional-dependencies]
ceda = [
    "httpx>=0.28.1",
    "httpx-auth>=0.23.1",
]
globus = [
    "boto3>=1.35.49",
    "globus-sdk>=3.46.0",
    "jsonpatch>=1.33",
]

[tool.poetry]
packages = [
    { include = "src" }
]
package-mode = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
